name: Deploy

on:
  push:
    branches: [main]
    
jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: Change directory
        run: cd ${{ secrets.REPO_PATH }}
        
      - name: Down container
        run: docker compose down
    
      - name: Down container
        run: docker compose up -d