name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: Run Deploy
        run: |
          cd ${{ secrets.REPO_PATH }}
          eval "$(ssh-agent -s)"
          ssh-add ${{ secrets.SSH_PRIVATE_KEY_PATH }}
          git pull origin main
          docker compose --profile prod down
          docker compose --profile prod up -d
