name: Deploy

on:
  push:
    branches: [main]
    
jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: Run docker compose
        run: |
          cd ${{ secrets.REPO_PATH }}
          docker compose down
          docker compose up -d